# Generated by Django 5.2.3 on 2025-07-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhotelroom',
            name='free_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='free_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
