# Generated by Django 5.2.3 on 2025-07-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_historicalhotelroom_free_rooms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelfood',
            old_name='price',
            new_name='price_b2b',
        ),
        migrations.RemoveField(
            model_name='historicalhotelroom',
            name='price',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='price',
        ),
        migrations.RemoveField(
            model_name='hotelservice',
            name='price',
        ),
        migrations.AddField(
            model_name='historicalhotelroom',
            name='price_b2b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhotelroom',
            name='price_b2c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelfood',
            name='price_b2c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='price_b2b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='price_b2c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='price_b2b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='price_b2c',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
