# Generated by Django 5.2.3 on 2025-07-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotelimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhotelroom',
            name='free_rooms',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='free_rooms',
        ),
        migrations.AddField(
            model_name='historicalhotelroom',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalhotelroom',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='description_en',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='description_ru',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='description_uz',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tourism/hotel/room'),
        ),
        migrations.AddField(
            model_name='hotelroomtype',
            name='description_en',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='hotelroomtype',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='hotelservicetype',
            name='description_en',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='hotelservicetype',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='hoteltype',
            name='description_en',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='hoteltype',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
