# Generated by Django 5.2.3 on 2025-07-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_historicalhotelroom_free_rooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhotelroom',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='description_uz',
        ),
    ]
