# Generated by Django 5.2.3 on 2025-07-16 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_remove_historicalhotelroom_description_and_more'),
        ('tourism', '0015_country_name_en_day_desc_en_day_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelimage',
            options={'verbose_name': 'Фото отеля', 'verbose_name_plural': 'Фото отеля'},
        ),
        migrations.AddField(
            model_name='historicalhotelroom',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhotelroom',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='historicalhotelroom',
            name='price_b2b',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена (B2B)'),
        ),
        migrations.AlterField(
            model_name='historicalhotelroom',
            name='price_b2c',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена (B2C)'),
        ),
        migrations.AlterField(
            model_name='historicalhotelroom',
            name='room',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hotel.hotelroomtype', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tourism.region', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hoteltype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='hotelfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tourism.food', verbose_name='Питание'),
        ),
        migrations.AlterField(
            model_name='hotelfood',
            name='price_b2b',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена (B2B)'),
        ),
        migrations.AlterField(
            model_name='hotelfood',
            name='price_b2c',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена (B2C)'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tourism/hotel/room', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='price_b2b',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена (B2B)'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='price_b2c',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена (B2C)'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.hotelroomtype', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='price_b2b',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена (B2B)'),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='price_b2c',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена (B2C)'),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.hotelservicetype', verbose_name='Услуга'),
        ),
    ]
