# Generated by Django 5.2.3 on 2025-07-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_hotelimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='description_en',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='description_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='description_uz',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='HistoricalHotelRoom',
        ),
    ]
