# Generated by Django 5.2.3 on 2025-07-17 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_hotelroom_description_en_hotelroom_description_ru_and_more'),
        ('tourism', '0015_country_name_en_day_desc_en_day_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tourism.food', verbose_name='Питание'),
        ),
    ]
