# Generated by Django 4.1.5 on 2025-03-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleuser',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
