# Generated by Django 4.1.5 on 2025-03-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(blank=True, null=True)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('iftor', 'Iftor'), ('saxar', 'Saxar'), ('hayit', 'Hayit')], max_length=255)),
            ],
        ),
    ]
