# Generated by Django 4.1.5 on 2025-03-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='type',
            field=models.CharField(choices=[('roza', 'Roza'), ('hayit', 'Hayit')], max_length=255),
        ),
    ]
