# Generated by Django 4.1.5 on 2025-02-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_country_price_per_order_client_order_name_and_more'),
        ('oauth', '0003_remove_user_username_user_opt_user_opt_lia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='countries',
            field=models.ManyToManyField(blank=True, to='order.country'),
        ),
    ]
