# Generated by Django 4.1.5 on 2025-02-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('oauth', '0004_user_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='countries',
        ),
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(blank=True, to='company.company'),
        ),
    ]
