# Generated by Django 4.1.5 on 2025-03-08 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_alter_user_phone_telegramuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
