# Generated by Django 4.1.5 on 2025-02-07 13:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('org_name', models.CharField(max_length=100)),
                ('org_stir', models.CharField(max_length=100)),
                ('send_org', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('departure_datetime', 'Yolga chiqdi'), ('enter_uzb_datetime', 'UZBga keldi'), ('process_customs_datetime', 'Tamojnada'), ('process_local_datetime', 'Dastavkada'), ('received_datetime', 'Yetkasib berildi')], default='departure_datetime', max_length=50, verbose_name='Статус')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.country')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=100, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('departure_datetime', models.DateTimeField(blank=True, null=True)),
                ('enter_uzb_datetime', models.DateTimeField(blank=True, null=True)),
                ('process_customs_datetime', models.DateTimeField(blank=True, null=True)),
                ('process_local_datetime', models.DateTimeField(blank=True, null=True)),
                ('process_received_datetime', models.DateTimeField(blank=True, null=True)),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.part')),
            ],
        ),
    ]
