# Generated by Django 4.1.5 on 2025-02-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_part_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='facture_price',
            field=models.FloatField(null=True),
        ),
    ]
