# Generated by Django 4.1.5 on 2025-02-17 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
