# Generated by Django 4.1.5 on 2025-02-17 08:53

import cargo.order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_part_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(default=cargo.order.models._generate_order_number, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('create_time', 'Sozdan'), ('departure_datetime', 'Yolga chiqdi'), ('enter_uzb_datetime', 'UZBga keldi'), ('process_customs_datetime', 'Tamojnada'), ('process_local_datetime', 'Dastavkada'), ('process_received_datetime', 'Yetkasib berildi')], default='create_time', max_length=50, verbose_name='Статус'),
        ),
    ]
