# Generated by Django 4.1.5 on 2025-02-22 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('oauth', '0005_remove_user_countries_user_companies'),
        ('order', '0008_remove_order_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['-number']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='facture_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.country'),
        ),
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('create_time', 'Cоздан'), ('departure_datetime', 'Отправлено'), ('enter_uzb_datetime', 'Узбекистане'), ('process_customs_datetime', 'В Таможне'), ('process_local_datetime', 'В доставке'), ('process_received_datetime', 'Доставлен')], default='create_time', max_length=50, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.product'),
        ),
    ]
