# Generated by Django 4.1.5 on 2025-03-04 10:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
