# Generated by Django 5.2.3 on 2025-06-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regiontranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='regiontranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='tourtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tourtranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='typetranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='typetranslation',
            name='master',
        ),
        migrations.AddField(
            model_name='historicalregion',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltour',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='historicaltour',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltype',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='historicaltype',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='price',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='region',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_ru',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_uz',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tour',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='type',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='type',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='PriceTranslation',
        ),
        migrations.DeleteModel(
            name='RegionTranslation',
        ),
        migrations.DeleteModel(
            name='TourTranslation',
        ),
        migrations.DeleteModel(
            name='TypeTranslation',
        ),
    ]
