# Generated by Django 5.2.3 on 2025-06-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_alter_regiontranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprice',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprice',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='historicalregion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltour',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltour',
            name='type',
        ),
        migrations.RemoveField(
            model_name='historicaltype',
            name='history_user',
        ),
        migrations.AddField(
            model_name='price',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HistoricalDay',
        ),
        migrations.DeleteModel(
            name='HistoricalPrice',
        ),
        migrations.DeleteModel(
            name='HistoricalRegion',
        ),
        migrations.DeleteModel(
            name='HistoricalTour',
        ),
        migrations.DeleteModel(
            name='HistoricalType',
        ),
    ]
