# Generated by Django 5.2.3 on 2025-06-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_remove_historicalprice_history_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='description_ru',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='type',
            name='description_uz',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='type',
        ),
        migrations.AddField(
            model_name='tour',
            name='type',
            field=models.ManyToManyField(to='tourism.type', verbose_name='Тип'),
        ),
    ]
