# Generated by Django 5.2.3 on 2025-06-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_type_description_ru_type_description_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='desc',
            field=models.TextField(max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='day',
            name='desc_ru',
            field=models.TextField(max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='day',
            name='desc_uz',
            field=models.TextField(max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='day',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour/day', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='day',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='day',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='day',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
