# Generated by Django 5.2.3 on 2025-06-16 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_day_desc_day_desc_ru_day_desc_uz_day_image_day_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('can_from', models.BooleanField(default=True, verbose_name='Откуда (показать?)')),
                ('can_to', models.BooleanField(default=True, verbose_name='Куда (показать?)')),
                ('active', models.BooleanField(default=True, verbose_name='Актив?')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страна',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('code', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
        ),
        migrations.CreateModel(
            name='HotelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.PositiveIntegerField(verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='day',
            name='image',
            field=models.ImageField(null=True, upload_to='tour/day', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='day',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tourism.region', verbose_name='Где будеть?'),
        ),
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tourism.country'),
        ),
        migrations.AddField(
            model_name='tour',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tourism.food'),
        ),
        migrations.AddField(
            model_name='day',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tourism.hotel'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.hoteltype'),
        ),
    ]
