# Generated by Django 5.2.3 on 2025-06-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_country_name_ru_country_name_uz_food_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='tourism/image', verbose_name='Фото')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Питание', 'verbose_name_plural': 'Питании'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
        migrations.AlterModelOptions(
            name='hoteltype',
            options={'verbose_name': 'Тип отеля', 'verbose_name_plural': 'Тип отели'},
        ),
    ]
