# Generated by Django 5.2.3 on 2025-06-16 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0008_image_alter_food_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tourism.tour'),
        ),
    ]
