# Generated by Django 5.2.3 on 2025-06-16 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0009_image_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='from_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_country_tour_set', to='tourism.country'),
        ),
        migrations.AddField(
            model_name='tour',
            name='to_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_country_tour_set', to='tourism.country'),
        ),
        migrations.AddField(
            model_name='tour',
            name='with_flight',
            field=models.BooleanField(default=False, verbose_name='Учитивая международный перелети'),
        ),
    ]
