# Generated by Django 5.2.3 on 2025-06-17 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0010_tour_from_country_tour_to_country_tour_with_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tourism.region'),
        ),
        migrations.AddField(
            model_name='tour',
            name='services',
            field=models.ManyToManyField(blank=True, to='tourism.service'),
        ),
    ]
