# Generated by Django 5.2.3 on 2025-07-09 11:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0011_service_hotel_region_tour_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип Комната отеля',
                'verbose_name_plural': 'Тип Комната отели',
            },
        ),
        migrations.CreateModel(
            name='HotelServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип услуги отеля',
                'verbose_name_plural': 'Тип услуги отели',
            },
        ),
        migrations.CreateModel(
            name='HotelFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tourism.food')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.hotel')),
            ],
            options={
                'verbose_name': 'Питание отеля',
                'verbose_name_plural': 'Питание отели',
            },
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('free_rooms', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tourism.hotelroomtype')),
            ],
            options={
                'verbose_name': 'Комната отеля',
                'verbose_name_plural': 'Комната отели',
            },
        ),
        migrations.CreateModel(
            name='HistoricalHotelRoom',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('free_rooms', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tourism.hotel')),
                ('room', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tourism.hotelroomtype')),
            ],
            options={
                'verbose_name': 'historical Комната отеля',
                'verbose_name_plural': 'historical Комната отели',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.hotel')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tourism.hotelservicetype')),
            ],
            options={
                'verbose_name': 'Услуги отеля',
                'verbose_name_plural': 'Услуги отели',
            },
        ),
    ]
