# Generated by Django 5.2.3 on 2025-07-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0012_hotelroomtype_hotelservicetype_hotelfood_hotelroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='region',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='hotelfood',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='day',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotelservice',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotelfood',
            name='food',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='room',
        ),
        migrations.RemoveField(
            model_name='hotelservice',
            name='service',
        ),
        migrations.DeleteModel(
            name='HistoricalHotelRoom',
        ),
        migrations.DeleteModel(
            name='HotelType',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='HotelFood',
        ),
        migrations.DeleteModel(
            name='HotelRoom',
        ),
        migrations.DeleteModel(
            name='HotelRoomType',
        ),
        migrations.DeleteModel(
            name='HotelService',
        ),
        migrations.DeleteModel(
            name='HotelServiceType',
        ),
    ]
