# Generated by Django 5.2.3 on 2025-07-09 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('tourism', '0013_remove_hotel_region_remove_hotel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.hotel'),
        ),
    ]
