# Generated by Django 4.1.5 on 2025-02-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='myid_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.JSONField(default=dict),
        ),
    ]
