# Generated by Django 4.1.5 on 2025-02-22 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('api_customs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='compony',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
