# Generated by Django 4.1.5 on 2025-02-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_customs', '0002_system_compony'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='compony',
            new_name='company',
        ),
    ]
