# Generated by Django 4.1.5 on 2025-02-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='company/img'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sub',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
