# Generated by Django 4.1.5 on 2025-03-14 01:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0004_client_created_user'),
        ('cargo', '0002_alter_user_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CargoUser',
        ),
    ]
